from docx import Document
from docx.shared import RGBColor, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.style import WD_STYLE_TYPE

doc = Document()
# Create a character style for default run formatting
default_font_style = doc.styles.add_style('DefaultFont', WD_STYLE_TYPE.CHARACTER)
default_font_style.font.color.rgb = RGBColor(0, 0, 0)
default_font_style.font.size = Pt(8)

from docx.oxml.shared import OxmlElement
from docx.oxml.ns import qn

def set_cell_border(cell, border_name='all', border_size=8, border_color='000000', border_style='single'):
    """Set cell borders. border_name: 'top', 'bottom', 'left', 'right', or 'all'"""
    tcPr = cell._tc.get_or_add_tcPr()
    tcBorders = OxmlElement('w:tcBorders')
    
    sides = ['top', 'left', 'bottom', 'right'] if border_name == 'all' else [border_name]
    for side in sides:
        border = OxmlElement(f'w:{side}')
        border.set(qn('w:val'), border_style)
        border.set(qn('w:sz'), str(border_size))
        border.set(qn('w:color'), border_color)
        tcBorders.append(border)
    
    tcPr.append(tcBorders)
    return f"Cell border {border_name} set: {border_style} {border_size}/8 pt"

def set_cell_shading(cell, fill_color='FFFFFF'):
    """Set cell background color"""
    tcPr = cell._tc.get_or_add_tcPr()
    shading = OxmlElement('w:shd')
    shading.set(qn('w:fill'), fill_color)
    shading.set(qn('w:val'), 'clear')
    tcPr.append(shading)
    return f"Cell shading set: #{fill_color}"


p1 = doc.add_paragraph('')
p1.paragraph_format.line_spacing = 1.0
run = p1.add_run('EMPREENDIMENTO', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p1.add_run(': ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p2 = doc.add_paragraph('', style='Heading 1')
p2.paragraph_format.space_before = Pt(3.8)
p2.paragraph_format.line_spacing = 1.0
run = p2.add_run('Quadra', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run('______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run('Lote', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run('___________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run('Área', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run('___________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p2.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
p4 = doc.add_paragraph('')
p4.alignment = WD_ALIGN_PARAGRAPH.CENTER
p4.paragraph_format.space_before = Pt(2.8)
p4.paragraph_format.line_spacing = 1.5
run = p4.add_run('PROMITENTE(S COMPRADOR(A/ES)', style='DefaultFont')
run.bold = True
run.underline = True
run.font.size = Pt(8.0)
p5 = doc.add_paragraph('')
p5.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p5.paragraph_format.space_before = Pt(2.8)
p5.paragraph_format.line_spacing = 1.5
run = p5.add_run('PESSOA FÍSICA', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p5.add_run(' - ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p5.add_run('NOME COMPLETO', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p5.add_run(':', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p5.add_run('____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('_____________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('____________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('RG Nº', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('ÓRGÃO EXPEDIDOR UF', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(':', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p5.add_run('_______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(',', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' inscrito no CPF/MF sob o nº', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('__________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(', portador da CNH ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(', DETRAN/', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('__________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(', NACIONALIDADE', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('_____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('PROFISSÃO:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('____________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('ESTADO', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('CIVIL', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('Escolaridade: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('______________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('Tempo Profissão: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('_____________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('.  E-mail: : ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('_____________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('. Telefone: : ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('__________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p5.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p6 = doc.add_paragraph('')
p6.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p6.paragraph_format.space_before = Pt(2.8)
p6.paragraph_format.line_spacing = 1.5
run = p6.add_run('Se casado:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p6.add_run(' data de casamento', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run('_______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run(' ', style='DefaultFont')
run.underline = True
run.font.size = Pt(9.0)
run = p6.add_run(';Regime de bens: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run('___________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run('_______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p6.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p7 = doc.add_paragraph('')
p7.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p7.paragraph_format.space_before = Pt(2.8)
p7.paragraph_format.line_spacing = 1.5
run = p7.add_run('Possui Filhos (menores de idade, quantos?): : ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p7.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p7.add_run('____________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p7.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
p8 = doc.add_paragraph('')
p8.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p8.paragraph_format.space_before = Pt(2.8)
p8.paragraph_format.line_spacing = 1.5
run = p8.add_run('Se comunhão universal ou separação de bens após 1977- dados do pacto antenupcial:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p8.add_run(' Data:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' (', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('__/__/____', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(')', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' Livro', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('_______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('Folhas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('_______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' Cartório:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('____________-', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(' .', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('\n', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('Se união estável:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p8.add_run(' qualificar os dois normalmente e declarar que convivem em união estável ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('desde ___/____/_____, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('conforme doc (dados de escritura: Livro', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('____ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('Fls', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('_____, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('Data ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('___/___/_______, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('Cartório', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run(':___________________ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p8.add_run('ou contrato ou alegação do cliente) Se for mais de um comprador que não sejam casados, qualificar todos eles da forma acima.', style='DefaultFont')
run.font.size = Pt(8.0)
p9 = doc.add_paragraph('')
p9.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p9.paragraph_format.space_before = Pt(2.8)
p9.paragraph_format.line_spacing = 1.5
run = p9.add_run('CÔNJUGE', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.font.size = Pt(10.0)
run = p9.add_run(' NOME COMPLETO', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p9.add_run('_______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_______________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('RG Nº', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('___________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('E ÓRGÃO EXPEDIDOR UF: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('______________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' portador da CNH', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' , DETRAN', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('CPF: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('NACIONALIDADE', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('__________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('PROFISSÃO', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('ESTADO CIVIL ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('Residentes e domiciliados na Rua/Avenida', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____________________________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(', número', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('complemento', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(',', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('bairro', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('cidade', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_______________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('estado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('\n', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('E-mail: : ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('__________________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('. Telefone: : ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('_________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p9.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p10 = doc.add_paragraph('')
p10.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p10.paragraph_format.space_before = Pt(2.8)
p10.paragraph_format.line_spacing = 1.5
run = p10.add_run('Declaro(amos) sob as penas da lei e para os fins que se fizerem necessários que o email, o telefone e o endereço indicados são verdadeiros e desde já autorizo o recebimento de notificações, citações, ofertas e qualquer outros avisos por meio de sistema\xa0eletrônico.', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p11 = doc.add_paragraph('')
p11.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p11.paragraph_format.space_before = Pt(2.8)
p11.paragraph_format.line_spacing = 1.5
run = p11.add_run('SE FOR ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p11.add_run('PESSOA JURÍDICA', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p11.add_run(': NOME DA EMPRESA', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('____________________________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(', inscrita no CNPJ/MF sob o nº ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('___._____._______/___, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('neste ato representada na forma de seu documento constitutivo por NOME COMPLETO: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('_____________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('___________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('RG Nº', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('__________________ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('E ÓRGÃO EXPEDIDOR UF: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('CPF/MF: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('__________________ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('NACIONALIDADE', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('____________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('PROFISSÃO', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(':________________________ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('ESTADO CIVIL ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('_________ ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('com endereço no ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('___________________________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('. ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('\n', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('Q', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('ue', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(' através da(s) empresa(s) imobiliária no final mencionada(s), integrada(s) ao sistema de comercialização do empreendimento, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run('possuí o interesse em adquirir o referido Lote no empreendimento supracitado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(', nos termos do presente pré-contrato, nas condições abaixo apresentadas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p11.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
p12 = doc.add_paragraph('')
p12.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p12.paragraph_format.space_before = Pt(2.8)
p12.paragraph_format.line_spacing = 1.5
run = p12.add_run(' ', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p12.add_run('Condições de venda a serem submetidas à aprovação da ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p12.add_run('VENDEDORA', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p12.add_run(' e que poderão ser modificadas por ela para que se adeque à Tabela de Vendas vigente', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p12.add_run(':', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p13 = doc.add_paragraph('', style='Body Text')
p13.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p13.paragraph_format.line_spacing = 1.0
run = p13.add_run('      ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p13.add_run('  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p13.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p13.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p14 = doc.add_paragraph('', style='Body Text')
p14.style = 'List Bullet'
p14.paragraph_format.space_before = Pt(0)
p14.paragraph_format.space_after = Pt(0)
p14.paragraph_format.line_spacing_rule = 0
p14.paragraph_format.line_spacing = 0
p14.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p14.paragraph_format.line_spacing = 1.0
run = p14.add_run('Valor imóvel à vista', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p14.add_run(':', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p14.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p14.add_run('__________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
p15 = doc.add_paragraph('', style='Body Text')
p15.style = 'List Bullet'
p15.paragraph_format.space_before = Pt(0)
p15.paragraph_format.space_after = Pt(0)
p15.paragraph_format.line_spacing_rule = 0
p15.paragraph_format.line_spacing = 0
p15.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p15.paragraph_format.line_spacing = 1.0
run = p15.add_run('Valor imóvel financiado – com juros:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p15.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p15.add_run('_____________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p15.add_run('      ', style='DefaultFont')
run.font.size = Pt(8.0)
p16 = doc.add_paragraph('', style='Heading 1')
p16.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p16.paragraph_format.space_before = Pt(6.7)
p16.paragraph_format.line_spacing = 1.0
run = p16.add_run('1', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(') Valor ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('de Arras Confirmatórias', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('/Sinal', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('__', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('___', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(' em ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run(' parcelas, com o vencimento da primeira parcela no dia  ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p16.add_run('___', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p16.add_run('/', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p16.add_run('___/____', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p16.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p17 = doc.add_paragraph('', style='Heading 1')
p17.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p17.paragraph_format.space_before = Pt(6.0)
p17.paragraph_format.line_spacing = 1.0
run = p17.add_run('2', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(') Saldo Financiado:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run('__________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run('em ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run('________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' parcelas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' mensais, com o vencimento da primeira parcela no dia ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p17.add_run('___', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p17.add_run('/', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p17.add_run('___/____', style='DefaultFont')
run.underline = True
run.font.size = Pt(8.0)
run = p17.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p18 = doc.add_paragraph('', style='Body Text')
p18.paragraph_format.space_before = Pt(6.0)
p18.paragraph_format.line_spacing = 1.0
run = p18.add_run('2', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('.1) Dia escolhido para o vencimento das parcelas: ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('(  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('5', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
run = p18.add_run('     ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('( ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('  ) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('10 ', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
run = p18.add_run('   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('(   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(') ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('15 ', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
run = p18.add_run('   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('(   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(')', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
run = p18.add_run('20', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
run = p18.add_run('    ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('( ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run(') ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p18.add_run('25', style='DefaultFont')
run.bold = True
run.font.size = Pt(10.0)
p19 = doc.add_paragraph('', style='Body Text')
p19.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p19.paragraph_format.space_before = Pt(6.0)
p19.paragraph_format.line_spacing = 1.0
run = p19.add_run('2', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('.2) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('Valor', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('d', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('e cada', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('p', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run('arcela:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p19.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('__________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('.O(s) PROMITENTE(S) COMPRADOR(A/ES) está(ão) ciente(s) e concorda(m) expressamente que sobre ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('o valor da parcela ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('já está pré-calculado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run(' juros a uma taxa efetiva de 12% (doze por', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('cento) ao ano, calculados de acordo com o Sistema Francês de Amortização (“Tabela Price”)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p19.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p20 = doc.add_paragraph('', style='Body Text')
p20.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p20.paragraph_format.space_before = Pt(6.0)
p20.paragraph_format.line_spacing = 1.0
run = p20.add_run('2', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p20.add_run('.3) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p20.add_run('Da correção monetária das parcelas: ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p20.add_run('As parcelas do Saldo Financiado serão corrigidas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p20.add_run(' pelo Índice Nacional de Preços ao Consumidor Amplo (IPCA)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p20.add_run(', sendo correção ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p20.add_run('(i) anual', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p20.add_run(' para os parcelamentos em até 36 (trinta e seis) meses; ou ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p20.add_run('(ii) mensal', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p20.add_run(' para os parcelamentos a partir de 37 (trinta e sete) meses', style='DefaultFont')
run.font.size = Pt(8.0)
run = p20.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p22 = doc.add_paragraph('')
p22.paragraph_format.line_spacing = 1.0
run = p22.add_run('Assinatura por:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p22.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p22.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p22.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p22.add_run('\tAssinatura do Contrato:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p23 = doc.add_paragraph('')
p23.paragraph_format.line_spacing = 1.0
run = p23.add_run('(    )', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p23.add_run(' ', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p23.add_run('Procuração\xa0\xa0', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p23.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p23.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p23.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p23.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p23.add_run('(    )', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p23.add_run(' ', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p23.add_run('Físico', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p24 = doc.add_paragraph('')
p24.paragraph_format.line_spacing = 1.0
run = p24.add_run('(    )', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p24.add_run(' ', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p24.add_run('Pelo próprio titular\xa0', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p24.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p24.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p24.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p24.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p24.add_run('(    )', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p24.add_run(' ', style='DefaultFont')
run.bold = True
run.italic = True
run.font.size = Pt(8.0)
run = p24.add_run('Por certificado digital', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p26 = doc.add_paragraph('')
p26.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p26.paragraph_format.space_before = Pt(2.8)
p26.paragraph_format.line_spacing = 1.5
run = p26.add_run('Moradia Atual (alugada, propria quitada/financiada, aluguel, casa dos pais):  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p26.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('. : Intenção Compra: Morar ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('(   )', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('. Investir ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('(', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('   ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run(')', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p26.add_run('.', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p27 = doc.add_paragraph('')
p27.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p27.paragraph_format.line_spacing = 1.0375
run = p27.add_run('DA ANÁLISE DE CRÉDITO', style='DefaultFont')
run.bold = True
run.underline = True
run.font.size = Pt(8.0)
run = p27.add_run(':', style='DefaultFont')
run.bold = True
run.underline = True
run.font.size = Pt(8.0)
p28 = doc.add_paragraph('', style='List Paragraph')
p28.style = 'List Bullet'
p28.paragraph_format.space_before = Pt(0)
p28.paragraph_format.space_after = Pt(0)
p28.paragraph_format.line_spacing_rule = 0
p28.paragraph_format.line_spacing = 0
p28.paragraph_format.line_spacing = 1.0375
run = p28.add_run('Prazo para Envio de Documentos: ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p28.add_run('O(s) PROMITENTE(S) COMPRADOR(A/ES) compromete(m)-se a encaminhar à VENDEDORA todos os documentos necessários para a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p28.add_run(' confirmação da', style='DefaultFont')
run.font.size = Pt(8.0)
run = p28.add_run(' análise de crédito no prazo de 48 (quarenta e oito) horas a partir da data de assinatura deste contrato. Caso os documentos não sejam enviados no referido prazo, o presente instrumento será rescindido automaticamente, retendo a VENDEDORA o Sinal pago.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p28.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
p29 = doc.add_paragraph('', style='List Paragraph')
p29.style = 'List Bullet'
p29.paragraph_format.space_before = Pt(0)
p29.paragraph_format.space_after = Pt(0)
p29.paragraph_format.line_spacing_rule = 0
p29.paragraph_format.line_spacing = 0
p29.paragraph_format.line_spacing = 1.0375
run = p29.add_run('Documentação Necessária: ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('A lista de documentos necessários para a análise de crédito será fornecida pel', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('o(a)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('Corretor(a) que está intermediando a presente negociação', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(', sendo os seguintes: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('a)', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('cópia do RG ou Carteira Profissional', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' autenticado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('; ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('b) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('Cópia do CPF ou CNH', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' autenticado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('; ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('c) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('Cópia da certidão de casamento ou declaração de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('união', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('estável', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('(com', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('ou', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('sem', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('averbação', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('divórcio)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ou ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('Certidão de Nascimento', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' atualizada', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(';', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('d)', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('Comprovante', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('residência', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('com', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('no', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('máximo', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('90', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('(noventa)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('dias; ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('e)', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run('comprovação', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('renda', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' dos últimos 3 (três) meses', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('; ou', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' sendo Pessoa Jurídica', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('f)', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' Contrato Social ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('atualizado; ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('g)', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p29.add_run(' Cartão CNPJ, certidão simplificada, procuração, se for o caso, bem como documentos a depender do caso em concreto', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' O(s) ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(' declara(m) ciência de que a análise de crédito só ocorrerá a partir do envio de TODOS os documentos necessários', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run(', podendo ser solicitado documentos adicionais a depender de cada caso', style='DefaultFont')
run.font.size = Pt(8.0)
run = p29.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p30 = doc.add_paragraph('', style='List Paragraph')
p30.style = 'List Bullet'
p30.paragraph_format.space_before = Pt(0)
p30.paragraph_format.space_after = Pt(0)
p30.paragraph_format.line_spacing_rule = 0
p30.paragraph_format.line_spacing = 0
p30.paragraph_format.line_spacing = 1.0375
run = p30.add_run('Condição Suspensiva:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p30.add_run(' A eficácia deste contrato está condicionada à aprovação bem-sucedida da análise de crédito do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('(s) ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('PROMITENTE(S) COMPRADOR(A/ES) pela VENDEDORA', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run(' Dessa forma e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('ste ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('instrumento ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('somente terá eficácia caso ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('o', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('(s) PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('seja', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('(m)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run(' aprovado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run('(s)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p30.add_run(' na análise de crédito pela VENDEDORA.', style='DefaultFont')
run.font.size = Pt(8.0)
p31 = doc.add_paragraph('', style='List Paragraph')
p31.style = 'List Bullet'
p31.paragraph_format.space_before = Pt(0)
p31.paragraph_format.space_after = Pt(0)
p31.paragraph_format.line_spacing_rule = 0
p31.paragraph_format.line_spacing = 0
p31.paragraph_format.line_spacing = 1.0375
run = p31.add_run('Negativa da Análise de Crédito:', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p31.add_run(' Em caso de ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('negativa', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' na análise de crédito, este ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('instrumento', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' não terá eficácia, ficando ambas as partes liberadas de quaisquer obrigações futuras decorrentes deste instrumento.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' Nesta hipótese', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' de ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('negativa ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('na análise de crédito, o', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('(s)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p31.add_run('perderá o direito ao valor pago a título de Sinal de Negócio, o qual será retido pela VENDEDORA a título de compensação pelos custos administrativos e comerciais incorridos.', style='DefaultFont')
run.font.size = Pt(8.0)
p32 = doc.add_paragraph('')
p32.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p32.paragraph_format.line_spacing = 1.0375
run = p32.add_run('DAS ARRAS CONFIRMATÓRIAS:', style='DefaultFont')
run.bold = True
run.underline = True
run.font.size = Pt(8.0)
p33 = doc.add_paragraph('', style='List Paragraph')
p33.style = 'List Bullet'
p33.paragraph_format.space_before = Pt(0)
p33.paragraph_format.space_after = Pt(0)
p33.paragraph_format.line_spacing_rule = 0
p33.paragraph_format.line_spacing = 0
p33.paragraph_format.line_spacing = 1.0375
run = p33.add_run('Do Sinal de Arras Confirmatória: ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p33.add_run('Sem prejuízo ao caráter irretratável e irrevogável do presente ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('instrumento, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('destaca-se que ele é realizado com a convenção de ARRAS CONFIRMATÓRIAS, de acordo com os artigos 418 e ss. do Código Civil Brasileiro. Desta forma, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('o(s)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' têm ciência de que', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' em c', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('aso', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' de ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('desistência e/ou não cumprimento de alguma de suas obrigações dispostas neste Instrumento', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p33.add_run(', ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('VENDEDORA', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' poderá denunciar o presente ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('instrumento', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' e tê-lo por desfeito, hipótese na qual ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('VENDEDORA', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' reterá o valor de Arras recebido, devendo restituir ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('ao(s)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' PROMITENTE', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('(S)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' COMPRADOR', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('(', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('A', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run(' os demais valores recebidos até o momento da rescisão', style='DefaultFont')
run.font.size = Pt(8.0)
run = p33.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p34 = doc.add_paragraph('', style='List Paragraph')
p34.style = 'List Bullet'
p34.paragraph_format.space_before = Pt(0)
p34.paragraph_format.space_after = Pt(0)
p34.paragraph_format.line_spacing_rule = 0
p34.paragraph_format.line_spacing = 0
p34.paragraph_format.line_spacing = 1.0375
run = p34.add_run('Do pagamento da comissão de corretagem', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p34.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' A', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' efetiva aquisição do lote objeto deste instrumento está sujeita à verificação de ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run('condição ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run('suspensiva', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(',', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' nos termos dos artigos 125 e seguintes do Código Civil, isto é, está sujeita ao pagamento integral:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run('\t', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' do valor das Arras previsto no', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' item', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(') e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(' da comissão de corretagem e sinal de negócio', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run(', sendo que o não pagamento ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run('nas datas aprazadas implicará na resolução automática do presente instrumento, independentemente de qualquer notificação ou interpelação contratual, de modo que a presente contratação não terá qualquer eficácia, ficando ambas as Partes desobrigadas de todos os seus termos, sem prejuízo das Arras e comissão pagas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p34.add_run('.', style='DefaultFont')
run.font.size = Pt(8.0)
p36 = doc.add_paragraph('')
p36.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p36.paragraph_format.line_spacing = 1.0375
run = p36.add_run('DAS DISPOSIÇÕES GERAIS:', style='DefaultFont')
run.bold = True
run.underline = True
run.font.size = Pt(8.0)
p37 = doc.add_paragraph('', style='Body Text')
p37.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
p37.paragraph_format.line_spacing = Pt(10.25)
run = p37.add_run('Ao', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('assinar', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('o', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('presente', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('Pré-Contrato', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('Compra', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('Venda,', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('o(a/os)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p37.add_run('declara(m):', style='DefaultFont')
run.font.size = Pt(8.0)
p38 = doc.add_paragraph('', style='List Paragraph')
p38.style = 'List Bullet'
p38.paragraph_format.space_before = Pt(0)
p38.paragraph_format.space_after = Pt(0)
p38.paragraph_format.line_spacing_rule = 0
p38.paragraph_format.line_spacing = 0
p38.paragraph_format.line_spacing = 1.0375
run = p38.add_run('Que o presente ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run('instrumento ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run('é celebrado em caráter irrevogável e irretratável e obriga entre si, seus herdeiros e sucessores a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run('qualquer', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p38.add_run('título.', style='DefaultFont')
run.font.size = Pt(8.0)
p39 = doc.add_paragraph('', style='List Paragraph')
p39.style = 'List Bullet'
p39.paragraph_format.space_before = Pt(0)
p39.paragraph_format.space_after = Pt(0)
p39.paragraph_format.line_spacing_rule = 0
p39.paragraph_format.line_spacing = 0
p39.paragraph_format.space_before = Pt(0.2)
p39.paragraph_format.line_spacing = 1.0375
run = p39.add_run('Que', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('compra', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('respectivo', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('imóvel', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('foi', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('intermediada', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('pela', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Imobiliária ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('inscrita no CNPJ sob o nº.: ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('_____________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('e no CRECI – ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('ª Região – ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('_______', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('sob o nº', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('____________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(',', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('através', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('seu  ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Corretor(a),', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Sr.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('(a)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('____________________________________________________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(',', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('inscrito', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('no', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('CRECI', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('–', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('_____________-', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('sob', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('o', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('nº.:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(':', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('_______________', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('-F', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('. O valor da comissão de corretagem ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('no', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('caso', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('distrato', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Pré-Contrat', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('o ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('             ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('ou', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Contrato', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Compra', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('Venda', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('tal', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('valor', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('não', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('será', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('objeto', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('devolução', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('em', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('nenhuma', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run('hipótese', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(', tendo em vista que a comissão de corretagem integra o valor do imóvel', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' nos termos do art. 67-A, i, da Lei 13.786/2018', style='DefaultFont')
run.font.size = Pt(8.0)
run = p39.add_run(' e art. 32-A, V, da mesma Lei.', style='DefaultFont')
run.font.size = Pt(8.0)
p40 = doc.add_paragraph('', style='List Paragraph')
p40.style = 'List Bullet'
p40.paragraph_format.space_before = Pt(0)
p40.paragraph_format.space_after = Pt(0)
p40.paragraph_format.line_spacing_rule = 0
p40.paragraph_format.line_spacing = 0
p40.paragraph_format.space_before = Pt(0.3)
p40.paragraph_format.line_spacing = 1.0375
run = p40.add_run('Estar', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('ciente', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run(' ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('que o', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run(' valor ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('da Comissão de Corretagem ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('será pago diretamente ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('pelo(a/s) COMPRADOR(A/ES) ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('para a Imobiliária e/ou Corretor(a) de Imóveis que está intermediando a presente negociação, ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p40.add_run('logo, este valor não intregrará o preço do imóvel e não será objeto de devolução pela VENDEDORA sob qualquer hipótese.', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p41 = doc.add_paragraph('', style='List Paragraph')
p41.style = 'List Bullet'
p41.paragraph_format.space_before = Pt(0)
p41.paragraph_format.space_after = Pt(0)
p41.paragraph_format.line_spacing_rule = 0
p41.paragraph_format.line_spacing = 0
p41.paragraph_format.space_before = Pt(0.3)
p41.paragraph_format.line_spacing = 1.0375
run = p41.add_run('Estar ciente de que o Contrato de Compra e Venda a ser formalizado após a devida aprovação da análise de crédito, deverá ser assinado com firma reconhecida pelo(s) PROMITENTE(S) COMPRADOR(A/ES), bem como os documentos pessoais (RG, CNH e CPF) que deverão ser autenticados em cartório. As custas de reconhecimento das assinaturas e da autenticação dos documentos, serão exclusivamente do(s) PROMITENTE(S) COMPRADOR(A/ES).  ', style='DefaultFont')
run.font.size = Pt(8.0)
p42 = doc.add_paragraph('', style='List Paragraph')
p42.style = 'List Bullet'
p42.paragraph_format.space_before = Pt(0)
p42.paragraph_format.space_after = Pt(0)
p42.paragraph_format.line_spacing_rule = 0
p42.paragraph_format.line_spacing = 0
p42.paragraph_format.space_before = Pt(0.3)
p42.paragraph_format.line_spacing = 1.0375
run = p42.add_run('Estar ciente de que a data escolhida para o vencimento das Parcelas do Saldo Financiado é inalterável.', style='DefaultFont')
run.font.size = Pt(8.0)
run = p42.add_run(' Caso o(s) PROMITENTE(S) COMPRADOR(A/ES) optem em alterar as datas de vencimentos dispostas neste instrumento, este PRÉ-CONTRATO será rescindido automaticamente, sob pena da retenção do Sinal de Arras pela VENDEDORA.', style='DefaultFont')
run.font.size = Pt(8.0)
p43 = doc.add_paragraph('', style='List Paragraph')
p43.style = 'List Bullet'
p43.paragraph_format.space_before = Pt(0)
p43.paragraph_format.space_after = Pt(0)
p43.paragraph_format.line_spacing_rule = 0
p43.paragraph_format.line_spacing = 0
p43.paragraph_format.space_before = Pt(0.3)
p43.paragraph_format.line_spacing = 1.0375
run = p43.add_run('Estar ciente de que com a eficácia do presente instrumento, o(s) PROMITENTE(S) COMPRADOR(A/ES) deverão encaminhar o Contrato de Compra e Venda com firma reconhecida à VENDEDORA, ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p43.add_run('no prazo de até 10 (dez) dias a contar da liberação da minuta ao Corretor de Imóveis que está intermedian', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p43.add_run('d', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p43.add_run('o a presente negociação', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p43.add_run('. Caso não seja cumprido tal prazo, o presente instrumento poderá ser rescindido automaticamente por inadimplemento do(s) PROMITENTE(S) COMPRADOR(A/ES).', style='DefaultFont')
run.font.size = Pt(8.0)
p44 = doc.add_paragraph('', style='List Paragraph')
p44.style = 'List Bullet'
p44.paragraph_format.space_before = Pt(0)
p44.paragraph_format.space_after = Pt(0)
p44.paragraph_format.line_spacing_rule = 0
p44.paragraph_format.line_spacing = 0
p44.paragraph_format.space_before = Pt(0.3)
p44.paragraph_format.line_spacing = 1.0375
run = p44.add_run('Estar ciente de que os boletos referentes ao Saldo Financiado só serão liberados pela VENDEDORA, após o(s) PROMITENTE(S) COMPRADOR(A/ES) encaminharem o Contrato de Compra e Venda com firma reconhecida à sede da VENDEDORA, sem prejuízo ao disposto no item anterior. Além disso, o(s) PROMITENTE(S) COMPRADOR(A/ES) estão cientes de que a assinatura do presente instrumento não viabiliza o envio por parte da VENDEDORA dos boletos referentes ao Saldo Financiado, sendo que o presente instrumento apenas viabiliza o envio dos boletos a título de Entrada. ', style='DefaultFont')
run.font.size = Pt(8.0)
p45 = doc.add_paragraph('', style='List Paragraph')
p45.style = 'List Bullet'
p45.paragraph_format.space_before = Pt(0)
p45.paragraph_format.space_after = Pt(0)
p45.paragraph_format.line_spacing_rule = 0
p45.paragraph_format.line_spacing = 0
p45.paragraph_format.space_before = Pt(0.3)
p45.paragraph_format.line_spacing = 1.0375
run = p45.add_run('Estar ciente de que em caso de inadimplemento de qualquer valor definido neste instrumento, o(s) PROMITENTE(S) COMPRADOR(A/ES) deverão ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('arcar', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('com:', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('a)correção', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('monetária', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('mensal', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('calculada', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('pelo', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('IPCA/IBGE;', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('b)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('juros', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('moratórios', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('diários', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('0,033%', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('(zero', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('vírgula', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('zero', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('trinta', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('três', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('por', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('cento),', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('limitado', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('1%', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('(um por', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('cento)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('ao', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('mês,', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('sem', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('prejuízo', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('da', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('incidência dos', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('juros', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('compensatórios, incluídos', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('no valor de cada parcela; c) multa de 2% (dois por cento) sobre o valor da parcela em atraso; e d) honorários', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('advogado, na', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('base', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('de', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('10%', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('(dez', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('por', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('cento) sobre', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('o valor do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('débito, e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('despesas', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('judiciais', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('e', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('extrajudiciais,', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('bem', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('como,', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('suportando', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('a', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('negativação', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('do', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('seu', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('nome', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('junto', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('aos', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('órgãos', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run(' ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p45.add_run('competentes.', style='DefaultFont')
run.font.size = Pt(8.0)
p46 = doc.add_paragraph('', style='List Paragraph')
p46.style = 'List Bullet'
p46.paragraph_format.space_before = Pt(0)
p46.paragraph_format.space_after = Pt(0)
p46.paragraph_format.line_spacing_rule = 0
p46.paragraph_format.line_spacing = 0
p46.paragraph_format.line_spacing = 1.0
run = p46.add_run('O(s) PROMITENTE(S) COMPRADOR(A/ES) ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p46.add_run('está(ão) ciente(s) e compreende(m) que, nos termos da LGPD de nº 13.709/2018, para a regular execução do Contrato de Compra e Venda, a VENDEDORA tratará os dados pessoais constantes na ficha cadastral e neste pré-contrato. Os dados são necessários para a execução do objeto do Contrato ou para atender a interesses legítimos da VENDEDORA, sempre que estes não se sobrepuserem aos direitos garantidos ao(s)', style='DefaultFont')
run.font.size = Pt(8.0)
run = p46.add_run(' PROMITENTE(S) COMPRADOR(A/ES).', style='DefaultFont')
run.font.size = Pt(8.0)
p47 = doc.add_paragraph('', style='List Paragraph')
p47.style = 'List Bullet'
p47.paragraph_format.space_before = Pt(0)
p47.paragraph_format.space_after = Pt(0)
p47.paragraph_format.line_spacing_rule = 0
p47.paragraph_format.line_spacing = 0
p47.paragraph_format.line_spacing = 1.0
run = p47.add_run('O(s) PROMITENTE(S) COMPRADOR(A/ES) ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p47.add_run(' desde já autorizam a VENDEDORA a compartilhar seus dados pessoais com o modelo de linguagem baseado em inteligência artificial fornecido pela Open AI que emprega medidas de segurança para proteger os dados pessoais compartilhados. O compartilhamento é exclusivamente para fins de auxílio na análise de crédito e confecção do Contrato Particular de Compra e Venda com Pacto de Alienação Fiduciária, ora objeto do presente\xa0pré-contrato.', style='DefaultFont')
run.font.size = Pt(8.0)
p48 = doc.add_paragraph('', style='List Paragraph')
p48.style = 'List Bullet'
p48.paragraph_format.space_before = Pt(0)
p48.paragraph_format.space_after = Pt(0)
p48.paragraph_format.line_spacing_rule = 0
p48.paragraph_format.line_spacing = 0
p48.paragraph_format.line_spacing = 1.0
run = p48.add_run('O(s) PROMITENTE(S) COMPRADOR(A/ES) ', style='DefaultFont')
run.font.size = Pt(8.0)
run = p48.add_run(' desde já autorizam a VENDEDORA a compartilhar seus dados pessoais com o modelo de linguagem baseado em inteligência artificial fornecido pela Open AI que emprega medidas de segurança para proteger os dados pessoais compartilhados. O compartilhamento é exclusivamente para fins de auxílio na análise de crédito e confecção do Contrato Particular de Compra e Venda com Pacto de Alienação Fiduciária, ora objeto do presente\xa0pré-contrato.', style='DefaultFont')
run.font.size = Pt(8.0)
p49 = doc.add_paragraph('')
p49.paragraph_format.line_spacing = 1.0
run = p49.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p49.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p49.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p49.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p49.add_run('\t                                  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
p50 = doc.add_paragraph('')
p50.alignment = WD_ALIGN_PARAGRAPH.RIGHT
p50.paragraph_format.line_spacing = 1.0375
run = p50.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('\t', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('\t                                  ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('______________', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run(', _______ ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('de ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('___________ ', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('de 202', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('5', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
run = p50.add_run('.', style='DefaultFont')
run.bold = True
run.font.size = Pt(8.0)
table1 = doc.add_table(rows=1, cols=2)
table1_cell_0_0 = table1.cell(0, 0)
table1_cell_0_0.text = ''
table1_cell_0_0_p1 = doc.add_paragraph('')
table1_cell_0_0_p1.alignment = WD_ALIGN_PARAGRAPH.CENTER
table1_cell_0_0_p1.paragraph_format.line_spacing = 1.0375
run = table1_cell_0_0_p1.add_run('PROMITENTE(S) COMPRADOR(A/ES)', style='DefaultFont')
run.font.size = Pt(8.0)
table1_cell_0_1 = table1.cell(0, 1)
table1_cell_0_1.text = ''
table1_cell_0_1_p1 = doc.add_paragraph('')
table1_cell_0_1_p1.alignment = WD_ALIGN_PARAGRAPH.CENTER
table1_cell_0_1_p1.paragraph_format.line_spacing = 1.0375
run = table1_cell_0_1_p1.add_run('CORRETOR RESPONSÁVEL PELA INTERMEDIAÇÃO', style='DefaultFont')
run.font.size = Pt(8.0)
doc.save("output.docx")